#!/bin/bash
set -e
########################################

ACTION=build

function set-variables-from-arguments () {
 case "$1" in
 
  ghc) 
     COMPILER=ghc
     PROJECT=cabal.project
     OUTPUT=dist-newstyle
  ;;
 
  ghcjs)
     COMPILER=ghcjs
     PROJECT=cabal-ghcjs.project
     OUTPUT=dist-ghcjs
  ;;
 
  *)
  ;;
 
 esac
}

########################################
# args

if   [ $# == 1 ]; then
  set-variables-from-arguments "$1"
  TARGET=all

elif [ $# == 2 ]; then
  set-variables-from-arguments "$1"
  TARGET="$2"

else
  echo '[Usage]'
  echo '    build COMPILER [TARGET[,TARGET...]]'
  echo
  echo '[Arguments]'
  echo
  echo 'COMPILER can be:'
  echo '  ghc'
  echo '  ghcjs'
  echo
  echo 'TARGET is `all` by default'
  echo 
  echo 'TARGET can be:'
  echo '  all'
  echo '  common'
  echo '  frontend'
  echo '  backend'
  echo
  echo 'or can any package in the new cabal `.project` files.'
  echo 'cat cabal.project' 
  cat cabal.project
  echo
  echo 'cat cabal-ghcjs.project' 
  cat cabal-ghcjs.project
  echo 
  echo '[Examples]'
  echo '    build ghc'
  echo '    build ghc   backend'
  echo '    build ghcjs frontend'
  echo '    build ghcjs common,frontend'
  echo
  exit 1
fi

########################################
# cmd

CABAL_COMMAND=(cabal "new-$ACTION" "$TARGET" "--project-file=$PROJECT" "--builddir=$OUTPUT")
# echo "${CABAL_COMMAND[@]}"

NIX_COMMAND=(nix-shell -A "shells.$COMPILER" --run '"'"${CABAL_COMMAND[@]}"'"')

echo [Running...]
echo "${NIX_COMMAND[@]}"
echo
eval ${NIX_COMMAND[@]}

########################################

# e.g. cabal new-build all --project-file=cabal-ghcjs.project --builddir=dist-ghcjs

# ACTION=build

# COMPILER=ghc
# PROJECT=cabal.project
# OUTPUT=dist-newstyle

# COMPILER=ghcjs
# PROJECT=cabal-ghcjs.project
# OUTPUT=dist-ghcjs

# TARGET=all

